######################################################################
##
## Filename: MP1_tb.udo
## Created on: Mon Sep 22 07:26:42 PM CDT 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
