######################################################################
##
## Filename: cmd_parse_tb.udo
## Created on: Mon Dec 15 03:07:14 PM CST 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
